---
version: 2
publish: &publish
  working_directory: ~/my-app
  docker:
    - image: circleci/node:14.0.0
  steps:
    - checkout

    - run:
        name: Installing dependencies
        command: npm ci

    - run:
        name: Login into Expo
        command: npx expo-cli login -u $Expo_UserID -p Messiah!

    - run:
        name: Publish to Expo
        command: npx expo-cli publish --max-old-space-size=4000 --non-interactive --max-workers 1 --release-channel default

jobs:
  publish_to_expo_dev:
    environment:
      EXPO_RELEASE_CHANNEL: dev
    <<: *publish

  publish_to_expo_prod:
    environment:
      EXPO_RELEASE_CHANNEL: default
    <<: *publish

workflows:
  version: 2
  my_app:
    jobs:
      - publish_to_expo_dev:
          filters:
            branches:
              only: development
      - publish_to_expo_prod:
          filters:
            branches:
              only: master